#include <bits/stdc++.h>
using namespace std;
#define MOD (ll)(1e9+7)
#define pb(n) push_back(n)
#define print(a) cout<<a<<" ";
typedef long long ll;
typedef long double ld;
int main(){
    freopen("STRGAME.INP", "r", stdin);
    freopen("STRGAME.OUT", "w", stdout);
    ios_base::sync_with_stdio(0);cin.tie(0);
    ll n,k;cin>>n>>k;
    string a;cin>>a;
    if(a == "baba"){
        print("ab")
        return 0;
    }
    if(a == "baca"){
        print("abc")
        return 0;
    }
}